#!/bin/sh

for i in xxd; do which $i || exit; done

CC='cc -O3 -Iinc'

#for i in bin2h; do [ ! -f "$i" ] && $CC "$i.c" -o "$i"; done

# mothfs
nasm mfs_hdr.s && \
xxd -i mfs_hdr > inc/mfs_hdr.h && \
$CC mfstool.c -o mfstool
